name: hlcm

model_type: segmented_locationchoice

segmentation_col: income_quartile

choosers_fit_filters:
- building_id > 0
- parcel_id > 0
- income > 0
- cid == 35
- b_year_built > 2000

choosers_predict_filters:
- cid == 35

alts_fit_filters:
- parcel_id > 0
- building_type_id > 0
- building_type_id < 3
- residential_units > 0
- sqft_per_unit > 0
- res_price_per_sqft > 0
- county_id == 35

alts_predict_filters:
- county_id == 35
- res_price_per_sqft > -1

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: is_mf + parcel_volume + np.log1p(low_income_500) + building_age + np.log1p(sfdu_1500) + np.log1p(jobs_5_within_10_min) + stream_dist + commute_time

models:
    1:
        fit_parameters:
            Coefficient:
                is_mf: 3.092519397770785
                parcel_volume: 0.0033177778990855
                np.log1p(low_income_500): 1.2686932075571835
                building_age: -0.130477820097156
                np.log1p(sfdu_1500): -2.1129202131572145
                np.log1p(jobs_5_within_10_min): 0.052958557564151
                stream_dist: 0.1871241256430721
                commute_time: -0.0111463112364753                
            Std. Error:
                is_mf: 3.092519397770785
                parcel_volume: 0.0033177778990855
                np.log1p(low_income_500): 1.2686932075571835
                building_age: -0.130477820097156
                np.log1p(sfdu_1500): -2.1129202131572145
                np.log1p(jobs_5_within_10_min): 0.052958557564151
                stream_dist: 0.1871241256430721
                commute_time: -0.0111463112364753
            T-Score:
                is_mf: 3.092519397770785
                parcel_volume: 0.0033177778990855
                np.log1p(low_income_500): 1.2686932075571835
                building_age: -0.130477820097156
                np.log1p(sfdu_1500): -2.1129202131572145
                np.log1p(jobs_5_within_10_min): 0.052958557564151
                stream_dist: 0.1871241256430721
                commute_time: -0.0111463112364753
        fitted: true
        log_likelihoods:
            convergence: -18417.244813030087
            'null': -58668.609012387744
            ratio: 0.6860800839995826
        model_expression: is_mf + parcel_volume + np.log1p(low_income_500) + building_age + np.log1p(sfdu_1500) + np.log1p(jobs_5_within_10_min) + stream_dist + commute_time - 1
        name: 1
    2:
        fit_parameters:
            Coefficient:              
                ave_income_1000: -0.58
                commute_time: -0.029
                university_dist: 0.052
                is_mf: 3.524
                parcel_volume: 0.002
                np.log1p(jobs_ind_1500): 0.044
                building_age: -0.13292806
                real_far: 0.033                
            Std. Error:
                ave_income_1000: -0.58
                commute_time: -0.029
                university_dist: 0.052
                is_mf: 3.524
                parcel_volume: 0.002
                np.log1p(jobs_ind_1500): 0.044
                building_age: -0.13292806
                real_far: 0.033
            T-Score:
                ave_income_1000: -0.58
                commute_time: -0.029
                university_dist: 0.052
                is_mf: 3.524
                parcel_volume: 0.002
                np.log1p(jobs_ind_1500): 0.044
                building_age: -0.13292806
                real_far: 0.033
        fitted: true
        log_likelihoods:
            convergence: -22865.369083556565
            'null': -58676.433058398594
            ratio: 0.6103142626137572
        model_expression: ave_income_1000 + commute_time + university_dist + is_mf + parcel_volume + np.log1p(jobs_ind_1500) + building_age + real_far - 1
        name: 2
    3:
        fit_parameters:
            Coefficient:              
                parcel_volume: 0.0154106408050513
                trail_dist: -0.2021876718612048
                building_age: -0.1424538654250856
                commute_time: -0.0149627095847234
                elevation: 0.0001947552935286                
            Std. Error:
                parcel_volume: 0.0154106408050513
                trail_dist: -0.2021876718612048
                building_age: -0.1424538654250856
                commute_time: -0.0149627095847234
                elevation: 0.0001947552935286
            T-Score:
                parcel_volume: 0.0154106408050513
                trail_dist: -0.2021876718612048
                building_age: -0.1424538654250856
                commute_time: -0.0149627095847234
                elevation: 0.0001947552935286
        fitted: true
        log_likelihoods:
            convergence: -34205.886142920346
            'null': -58672.52103539317
            ratio: 0.41700330002376673
        model_expression: parcel_volume + trail_dist + building_age + commute_time + elevation - 1
        name: 3
    4:
        fit_parameters:
            Coefficient:              
                building_age: -0.1395930366717611
                bus_rte_dist: 4.655186068104112e-05
                fwy_exit_dist_tdm_output: -0.1562522201490166
                parcel_volume: 0.0126512176186567
                stream_dist: 0.633644828169869
                trail_dist: -0.1886252425519858
                university_dist: 0.040480367323741
                commute_time: -0.0411628478391136
                airport_distance: 0.0378621598093669                
            Std. Error:
                building_age: -0.1395930366717611
                bus_rte_dist: 4.655186068104112e-05
                fwy_exit_dist_tdm_output: -0.1562522201490166
                parcel_volume: 0.0126512176186567
                stream_dist: 0.633644828169869
                trail_dist: -0.1886252425519858
                university_dist: 0.040480367323741
                commute_time: -0.0411628478391136
                airport_distance: 0.0378621598093669
            T-Score:
                building_age: -0.1395930366717611
                bus_rte_dist: 4.655186068104112e-05
                fwy_exit_dist_tdm_output: -0.1562522201490166
                parcel_volume: 0.0126512176186567
                stream_dist: 0.633644828169869
                trail_dist: -0.1886252425519858
                university_dist: 0.040480367323741
                commute_time: -0.0411628478391136
                airport_distance: 0.0378621598093669
        fitted: true
        log_likelihoods:
            convergence: -34138.30667778726
            'null': -58676.433058398594
            ratio: 0.41819390003119994
        model_expression: building_age + bus_rte_dist + fwy_exit_dist_tdm_output + parcel_volume + stream_dist + trail_dist + university_dist + commute_time + airport_distance - 1
        name: 4

fitted: true

probability_mode: single_chooser

choice_mode: aggregate

remove_alts: true
