name: hlcm

model_type: segmented_locationchoice

segmentation_col: income_quartile

choosers_fit_filters:
- building_id > 0
- parcel_id > 0
- income > 0
- cid == 49
- b_year_built > 2000

choosers_predict_filters:
- cid == 49

alts_fit_filters:
- parcel_id > 0
- building_type_id > 0
- building_type_id < 3
- residential_units > 0
- sqft_per_unit > 0
- res_price_per_sqft > 0
- county_id == 49
- building_age > 0

alts_predict_filters:
- county_id == 49
- res_price_per_sqft > -1

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 15000

prediction_sample_size: null

default_config:
    model_expression: building_age + bus_rte_dist + is_sf + jobs_1_500 + low_income_500 + parcel_volume + sfdu_1500

models:
    1:
        fit_parameters:
            Coefficient:
                building_age: -0.1030963051507341
                bus_rte_dist: -8.85570809717922e-06
                is_sf: -1.6346591369491388
                jobs_1_500: 0.304238238696485
                low_income_500: 1.6160234626958736
                parcel_volume: 0.0048492007414439
                sfdu_1500: -2.125124191162161                
            Std. Error:
                building_age: -0.1030963051507341
                bus_rte_dist: -8.85570809717922e-06
                is_sf: -1.6346591369491388
                jobs_1_500: 0.304238238696485
                low_income_500: 1.6160234626958736
                parcel_volume: 0.0048492007414439
                sfdu_1500: -2.125124191162161
            T-Score:
                building_age: -0.1030963051507341
                bus_rte_dist: -8.85570809717922e-06
                is_sf: -1.6346591369491388
                jobs_1_500: 0.304238238696485
                low_income_500: 1.6160234626958736
                parcel_volume: 0.0048492007414439
                sfdu_1500: -2.125124191162161
        fitted: true
        log_likelihoods:
            convergence: -34727.74079738298
            'null': -53684.691703476296
            ratio: 0.35311650872097256
        model_expression: building_age + bus_rte_dist + is_sf + jobs_1_500 + low_income_500 + parcel_volume + sfdu_1500 -1
        name: 1
    2:
        fit_parameters:
            Coefficient:
                res_price_per_sqft: 0.01
                parcel_volume: 0.004
                building_age: -0.1
                fwy_exit_dist_tdm_output: 0.059
                low_income_500: 0.441
                sfdu_1500: -1.418
                jobs_1_500: 0.281
                jobs_ind_1500: 0.123
                is_sf: -1.426
                ave_lot_size_per_unit: -0.177
                university_dist: 0.028
                trail_dist: -0.092                
            Std. Error:
                res_price_per_sqft: 0.01
                parcel_volume: 0.004
                building_age: -0.1
                fwy_exit_dist_tdm_output: 0.059
                low_income_500: 0.441
                sfdu_1500: -1.418
                jobs_1_500: 0.281
                jobs_ind_1500: 0.123
                is_sf: -1.426
                ave_lot_size_per_unit: -0.177
                university_dist: 0.028
                trail_dist: -0.092
            T-Score:
                res_price_per_sqft: 0.01
                parcel_volume: 0.004
                building_age: -0.1
                fwy_exit_dist_tdm_output: 0.059
                low_income_500: 0.441
                sfdu_1500: -1.418
                jobs_1_500: 0.281
                jobs_ind_1500: 0.123
                is_sf: -1.426
                ave_lot_size_per_unit: -0.177
                university_dist: 0.028
                trail_dist: -0.092
        fitted: true
        log_likelihoods:
            convergence: -39021.385100968786
            'null': -52976.61553949437
            ratio: 0.263422460955851
        model_expression: res_price_per_sqft + parcel_volume + building_age + fwy_exit_dist_tdm_output + low_income_500 + sfdu_1500 + jobs_1_500 + jobs_ind_1500 + is_sf + ave_lot_size_per_unit + university_dist + trail_dist - 1
        name: 2
    3:
        fit_parameters:
            Coefficient:
                fwy_exit_dist_tdm_output: 0.0131956930673349
                parcel_volume: 0.0138317051322183
                building_age: -0.0896173080487624
                sfdu_1500: -3.500830823656183
                high_income_1000: 4.378192897169119                
            Std. Error:
                fwy_exit_dist_tdm_output: 0.0131956930673349
                parcel_volume: 0.0138317051322183
                building_age: -0.0896173080487624
                sfdu_1500: -3.500830823656183
                high_income_1000: 4.378192897169119
            T-Score:
                fwy_exit_dist_tdm_output: 0.0131956930673349
                parcel_volume: 0.0138317051322183
                building_age: -0.0896173080487624
                sfdu_1500: -3.500830823656183
                high_income_1000: 4.378192897169119
        fitted: true
        log_likelihoods:
            convergence: -42846.516063325835
            'null': -53137.008482716796
            ratio: 0.1936596115066963
        model_expression: fwy_exit_dist_tdm_output + parcel_volume + building_age + sfdu_1500 + high_income_1000 - 1
        name: 3
    4:
        fit_parameters:
            Coefficient:
                building_age: -0.0936309430373758
                fwy_exit_dist_tdm_output: -0.0304666540760617
                parcel_volume: 0.0131970743308986
                stream_dist: -0.3905022603531566
                university_dist: 0.0144466746313857
                high_income_1000: 1.865217936802817
                elevation: 0.0009440711477362
                commute_time: -0.0069175669771116                
            Std. Error:
                building_age: -0.0936309430373758
                fwy_exit_dist_tdm_output: -0.0304666540760617
                parcel_volume: 0.0131970743308986
                stream_dist: -0.3905022603531566
                university_dist: 0.0144466746313857
                high_income_1000: 1.865217936802817
                elevation: 0.0009440711477362
                commute_time: -0.0069175669771116
            T-Score:
                building_age: -0.0936309430373758
                fwy_exit_dist_tdm_output: -0.0304666540760617
                parcel_volume: 0.0131970743308986
                stream_dist: -0.3905022603531566
                university_dist: 0.0144466746313857
                high_income_1000: 1.865217936802817
                elevation: 0.0009440711477362
                commute_time: -0.0069175669771116
        fitted: true
        log_likelihoods:
            convergence: -44724.488988060264
            'null': -53602.53922036237
            ratio: 0.16562741917512636
        model_expression: building_age + fwy_exit_dist_tdm_output + parcel_volume + stream_dist + university_dist + high_income_1000 + elevation + commute_time - 1
        name: 4

fitted: true

probability_mode: single_chooser

choice_mode: aggregate

remove_alts: true
