name: nrh_ret

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- unit_price_non_residential > 3
- unit_price_non_residential < 70
- year_built > 1880
- year_built < 2015
- building_sqft > 500
- sale_lease == 'lease'
- general_type == 'Retail'
- zone_id > 0
- node_id > 0
- lease_type == 'NNN'
- building_age < 200

predict_filters:
- county_id==11
- building_type_id==4
- zone_id > 0

min_segment_size: 10

default_config:
    model_expression: building_age + rail_stn_dist + parcel_volume + volume_two_way_nofwy + jobs_7_500

    ytransform: np.exp

models:
    Retail:
        fit_parameters:
            Coefficient:
                Intercept: 3.577802303721933
                building_age: -0.009666734019177
                rail_stn_dist: -0.000010752821399
                parcel_volume: 0.007069959226946
                volume_two_way_nofwy: -0.000010975383352
                jobs_7_500: -0.290817721792210
            Std. Error:
                Intercept: 3.577802303721933
                building_age: -0.009666734019177
                rail_stn_dist: -0.000010752821399
                parcel_volume: 0.007069959226946
                volume_two_way_nofwy: -0.000010975383352
                jobs_7_500: -0.290817721792210
            T-Score:
                Intercept: 3.577802303721933
                building_age: -0.009666734019177
                rail_stn_dist: -0.000010752821399
                parcel_volume: 0.007069959226946
                volume_two_way_nofwy: -0.000010975383352
                jobs_7_500: -0.290817721792210
        fit_rsquared: 0.310
        fit_rsquared_adj: 0.282
        fitted: true
        name: Retail

fitted: true
