name: nrh_ind

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- unit_price_non_residential > 3
- unit_price_non_residential < 35
- year_built > 1880
- year_built < 2015
- sale_lease == 'lease'
- general_type == 'Industrial'
- zone_id > 0
- node_id > 0
- lease_type == 'NNN'
- building_age < 200

predict_filters:
- county_id==49
- building_type_id==3
- zone_id > 0

min_segment_size: 10

default_config:
    model_expression: parcel_volume + university_dist + rail_depot + jobs_6_1000 + np.log1p(industrial_sqft_1000)

    ytransform: null

models:
    Industrial:
        fit_parameters:
            Coefficient:
                Intercept: 2.622261358151220
                parcel_volume: 0.002718326438732
                university_dist: 0.011587562860226
                rail_depot: -0.064372334826557
                jobs_6_1000: 0.078243810875863
                np.log1p(industrial_sqft_1000): -0.058167604482515
            Std. Error:
                Intercept: 2.622261358151220
                parcel_volume: 0.002718326438732
                university_dist: 0.011587562860226
                rail_depot: -0.064372334826557
                jobs_6_1000: 0.078243810875863
                np.log1p(industrial_sqft_1000): -0.058167604482515
            T-Score:
                Intercept: 2.622261358151220
                parcel_volume: 0.002718326438732
                university_dist: 0.011587562860226
                rail_depot: -0.064372334826557
                jobs_6_1000: 0.078243810875863
                np.log1p(industrial_sqft_1000): -0.058167604482515
        fit_rsquared: 0.210
        fit_rsquared_adj: 0.204
        fitted: true
        name: Industrial

fitted: true
