name: nrh_ind

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- unit_price_non_residential > 3
- unit_price_non_residential < 35
- year_built > 1880
- year_built < 2015
- sale_lease == 'lease'
- general_type == 'Industrial'
- zone_id > 0
- node_id > 0
- lease_type == 'NNN'
- building_age < 200

predict_filters:
- county_id==11
- building_type_id==3
- zone_id > 0

min_segment_size: 10

default_config:
    model_expression: rail_depot + rail_stn_dist + parcel_volume + university_dist + ave_sqft_per_unit_500 + population_within_30_min_transit + jobs_500 + mfdu_1000

    ytransform: null

models:
    Industrial:
        fit_parameters:
            Coefficient:
                Intercept: 2.231640710227948
                rail_depot: -0.190869539556835
                rail_stn_dist: 0.000004601720039
                parcel_volume: 0.008079390593816
                university_dist: 0.038840995522064
                ave_sqft_per_unit_500: -0.012821989470099
                population_within_30_min_transit: -0.000012826210591
                jobs_500: -0.282166253144905
                mfdu_1000: 0.049929108768175
            Std. Error:
                Intercept: 2.231640710227948
                rail_depot: -0.190869539556835
                rail_stn_dist: 0.000004601720039
                parcel_volume: 0.008079390593816
                university_dist: 0.038840995522064
                ave_sqft_per_unit_500: -0.012821989470099
                population_within_30_min_transit: -0.000012826210591
                jobs_500: -0.282166253144905
                mfdu_1000: 0.049929108768175
            T-Score:
                Intercept: 2.231640710227948
                rail_depot: -0.190869539556835
                rail_stn_dist: 0.000004601720039
                parcel_volume: 0.008079390593816
                university_dist: 0.038840995522064
                ave_sqft_per_unit_500: -0.012821989470099
                population_within_30_min_transit: -0.000012826210591
                jobs_500: -0.282166253144905
                mfdu_1000: 0.049929108768175
        fit_rsquared: 0.433
        fit_rsquared_adj: 0.403
        fitted: true
        name: Industrial

fitted: true
