name: nrh_ret

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- unit_price_non_residential > 3
- unit_price_non_residential < 70
- year_built > 1880
- year_built < 2015
- building_sqft > 500
- sale_lease == 'lease'
- general_type == 'Retail'
- zone_id > 0
- node_id > 0
- lease_type == 'NNN'
- building_age < 200

predict_filters:
- county_id==49
- building_type_id==4
- zone_id > 0

min_segment_size: 10

default_config:
    model_expression: building_age + logsumpopulation + ave_income_500 + jobs_1_500 + jobs_7_500 + jobs_3_1500 + np.log1p(population_within_10_min)

    ytransform: np.exp

models:
    Retail:
        fit_parameters:
            Coefficient:
                Intercept: 4.746094635459437
                building_age: -0.007170862480049
                logsumpopulation: 0.000002858821507
                ave_income_500: -0.013767970684375
                jobs_1_500: 0.314113913607042
                jobs_7_500: 0.272033825238968
                jobs_3_1500: -0.778292273581121
                np.log1p(population_within_10_min): -0.125615046647998
            Std. Error:
                Intercept: 4.746094635459437
                building_age: -0.007170862480049
                logsumpopulation: 0.000002858821507
                ave_income_500: -0.013767970684375
                jobs_1_500: 0.314113913607042
                jobs_7_500: 0.272033825238968
                jobs_3_1500: -0.778292273581121
                np.log1p(population_within_10_min): -0.125615046647998
            T-Score:
                Intercept: 4.746094635459437
                building_age: -0.007170862480049
                logsumpopulation: 0.000002858821507
                ave_income_500: -0.013767970684375
                jobs_1_500: 0.314113913607042
                jobs_7_500: 0.272033825238968
                jobs_3_1500: -0.778292273581121
                np.log1p(population_within_10_min): -0.125615046647998
        fit_rsquared: 0.417
        fit_rsquared_adj: 0.400
        fitted: true
        name: Retail

fitted: true
