name: rsh

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- county_id == 11
- building_type_id == 2
- res_price_per_sqft > 20.0
- res_price_per_sqft < 400.0
- 5000 > sqft_per_unit > 400
- 2020 > year_built > 1900
- residential_units < 200
- building_sqft > 800
- parcel_acres < 10
- 100000 < improvement_value < 10000000

predict_filters:
- county_id == 11
- sqft_per_unit > 0
- sqft_per_unit <= 5000
- building_type_id == 2
- residential_units > 0

min_segment_size: 10

default_config:
    model_expression: sqft_per_unit + land_value_per_acre + np.log1p(jobs_10_within_10_min) + np.log1p(jobs_within_20_min_transit)

    ytransform: np.exp

models:
    MF Residential:
        fit_parameters:
            Coefficient:
                Intercept: 4.867176674978992
                sqft_per_unit: -0.000100847709304
                land_value_per_acre: 0.000000181233814
                np.log1p(jobs_10_within_10_min): 0.034332655927875
                np.log1p(jobs_within_20_min_transit): 0.004576870054486
            Std. Error:
                Intercept: 4.867176674978992
                sqft_per_unit: -0.000100847709304
                land_value_per_acre: 0.000000181233814
                np.log1p(jobs_10_within_10_min): 0.034332655927875
                np.log1p(jobs_within_20_min_transit): 0.004576870054486
            T-Score:
                Intercept: 4.867176674978992
                sqft_per_unit: -0.000100847709304
                land_value_per_acre: 0.000000181233814
                np.log1p(jobs_10_within_10_min): 0.034332655927875
                np.log1p(jobs_within_20_min_transit): 0.004576870054486
        fit_rsquared: 0.510252593224381
        fit_rsquared_adj: 0.5095768756795692
        fitted: true
        name: MF Residential

fitted: true