name: rsh

model_type: segmented_regression

segmentation_col: general_type

fit_filters:
- county_id==35
- building_type_id == 1
- res_price_per_sqft > 20.0
- res_price_per_sqft < 800.0
- 10000> sqft_per_unit > 400
- 2020 > year_built > 1900
- residential_units < 100
- building_sqft > 800
- parcel_acres < 10
- 75000 < improvement_value < 1000000

predict_filters:
- county_id==35
- sqft_per_unit > 0
- sqft_per_unit <= 12000
- building_type_id == 1
- residential_units > 0

min_segment_size: 10

default_config:
    model_expression: sqft_per_unit + fwy_exit_dist_tdm_output + parcel_volume + airport_distance + trail_dist + jobs_5_500 + np.log1p(jobs_10_within_10_min) + np.log1p(population_within_10_min)

    ytransform: null

models:
    SF Residential:
        fit_parameters:
            Coefficient:
                Intercept: 5.787418593333184
                sqft_per_unit: -0.000103833681168
                fwy_exit_dist_tdm_output: -0.011741359308931
                parcel_volume: -0.001463617516179
                airport_distance: 0.019618155361188
                trail_dist: -0.013439789773871
                jobs_5_500: 0.021573903201761
                np.log1p(jobs_10_within_10_min): 0.033290394683206
                np.log1p(population_within_10_min): -0.080051094918364
            Std. Error:
                Intercept: 5.787418593333184
                sqft_per_unit: -0.000103833681168
                fwy_exit_dist_tdm_output: -0.011741359308931
                parcel_volume: -0.001463617516179
                airport_distance: 0.019618155361188
                trail_dist: -0.013439789773871
                jobs_5_500: 0.021573903201761
                np.log1p(jobs_10_within_10_min): 0.033290394683206
                np.log1p(population_within_10_min): -0.080051094918364
            T-Score:
                Intercept: 5.787418593333184
                sqft_per_unit: -0.000103833681168
                fwy_exit_dist_tdm_output: -0.011741359308931
                parcel_volume: -0.001463617516179
                airport_distance: 0.019618155361188
                trail_dist: -0.013439789773871
                jobs_5_500: 0.021573903201761
                np.log1p(jobs_10_within_10_min): 0.033290394683206
                np.log1p(population_within_10_min): -0.080051094918364
        fit_rsquared: 0.46249165473221565
        fit_rsquared_adj: 0.46220326808390855
        fitted: true
        name: SF Residential

fitted: true
