name: remm
channels:
  - conda-forge
  - defaults
dependencies:
  - blosc=1.21.3
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-blosc2=2.12.0
  - ca-certificates=2025.7.14
  - certifi=2025.7.14
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - expat=2.7.1
  - h2=4.2.0
  - hdf5=1.12.1
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icc_rt=2022.1.0
  - idna=3.10
  - joblib=1.5.1
  - libffi=3.4.4
  - lz4-c=1.9.4
  - lzo=2.10
  - numexpr=2.10.1
  - numpy=1.26.4
  - openssl=3.5.1
  - pandana=0.7
  - pandas=2.3.1
  - pip=25.1
  - py-cpuinfo=9.0.0
  - pycparser=2.22
  - pysocks=1.7.1
  - pytables=3.9.2
  - python=3.9.23
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2025.2
  - requests=2.32.4
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - affine==2.4.0
    - attrs==25.3.0
    - click==8.1.8
    - click-plugins==1.1.1.2
    - cligj==0.7.2
    - colorama==0.4.6
    - geopandas==1.0.1
    - importlib-metadata==8.7.0
    - orca-wfrc==0.0.5
    - packaging==25.0
    - patsy==1.0.1
    - prettytable==3.16.0
    - pyogrio==0.11.0
    - pyparsing==3.2.3
    - pyproj==3.6.1
    - pyyaml==6.0.2
    - rasterio==1.4.3
    - shapely==2.0.7
    - simpledbf==0.2.6
    - statsmodels==0.14.5
    - toolz==1.0.0
    - urbansim-wfrc==0.4.5
    - wcwidth==0.2.13
    - zbox==1.2.0
    - zipp==3.23.0